### ISSUE TITLE
serious bug on Ruby 1.9 - breaks gem install

### ISSUE THREAD

**Issue by grimen** [adamsanderson/open_gem#4] opened 2009-10-09 23:07 UTC
<pre>
sudo gem install technicalpickles-jeweler
Password:
/Users/grimen/.rvm/gems/ruby/1.9.1/gems/open_gem-1.4.0/lib/rubygems_plugin.rb:8:in `require': no such file to load -- open_gem/common_options (LoadError)
    from /Users/grimen/.rvm/gems/ruby/1.9.1/gems/open_gem-1.4.0/lib/rubygems_plugin.rb:8:in `<top (required)>'
    from /Users/grimen/.rvm/ruby-1.9.1-p243/lib/ruby/site_ruby/1.9.1/rubygems.rb:1136:in `load'
    from /Users/grimen/.rvm/ruby-1.9.1-p243/lib/ruby/site_ruby/1.9.1/rubygems.rb:1136:in `block in <top (required)>'
    from /Users/grimen/.rvm/ruby-1.9.1-p243/lib/ruby/site_ruby/1.9.1/rubygems.rb:1134:in `each'
    from /Users/grimen/.rvm/ruby-1.9.1-p243/lib/ruby/site_ruby/1.9.1/rubygems.rb:1134:in `<top (required)>'
    from <internal:gem_prelude>:225:in `require'
    from <internal:gem_prelude>:225:in `load_full_rubygems_library'
    from <internal:gem_prelude>:324:in `const_missing'
    from /Users/grimen/.rvm/ruby-1.9.1-p243/bin/gem:15:in `<main>'
</pre>

I can't even uninstall (had to remove open_gem manually to be able to use rubygems). Quite nasty...

**Comment by adamsanderson** [comment] 2009-10-10 00:38
I haven't ever used it with 1.9, I'll take a look.

**Comment by adamsanderson** [comment] 2009-10-10 00:43
As far as I can tell it works fine:

```
RockLobster:~ netghost$ sudo gem1.9 install open_gem
Successfully installed open_gem-1.4.0
1 gem installed
Installing ri documentation for open_gem-1.4.0...
Updating class cache with 1524 classes...
Installing RDoc documentation for open_gem-1.4.0...
RockLobster:~ netghost$ gem1.9 open open_gem
Open which gem?
 1. open_gem 1.3.1
 2. open_gem 1.4.0
```

I did notice that you seem to be running rvm.  Are you sure it's getting all the paths correct?

**Comment by grimen** [comment] 2009-10-10 01:07
open_gem works to open gems, but look above: gem install/uninstall fails. Try to install a gem.

**Comment by adamsanderson** [comment] 2009-10-10 15:44
With open_gem installed, I was able to install the `json` gem just fine as an example:

```
RockLobster:Projects netghost$ sudo gem1.9 list open

*** LOCAL GEMS ***

open_gem (1.4.0, 1.3.1)
RockLobster:Projects netghost$ sudo gem1.9 install json
Building native extensions.  This could take a while...
Successfully installed json-1.1.9
1 gem installed
Installing ri documentation for json-1.1.9...
Updating class cache with 1530 classes...
Installing RDoc documentation for json-1.1.9...
RockLobster:Projects netghost$
```

It unintsalled cleanly as well.  I then tried to reproduce your issue by installing jeweler:

```
RockLobster:Projects netghost$ sudo gem1.9 install technicalpickles-jeweler
Successfully installed git-1.2.4
Successfully installed json_pure-1.1.9
Successfully installed rubyforge-2.0.2
Successfully installed technicalpickles-jeweler-1.2.1
4 gems installed
Installing ri documentation for git-1.2.4...
Installing ri documentation for json_pure-1.1.9...
Installing ri documentation for rubyforge-2.0.2...
Installing ri documentation for technicalpickles-jeweler-1.2.1...
Installing RDoc documentation for git-1.2.4...
Installing RDoc documentation for json_pure-1.1.9...
Installing RDoc documentation for rubyforge-2.0.2...
Installing RDoc documentation for technicalpickles-jeweler-1.2.1...
RockLobster:Projects netghost$
```

With no ill effects.  Just for reference I attempted to reproduce your issue with the following configuration:

```
RockLobster:~ netghost$ gem1.9 --version
1.3.5
RockLobster:~ netghost$ ruby1.9 --version
ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-darwin10]
```

**Comment by grimen** [comment] 2009-10-10 15:58
Well don't know, this is the only gem that fails out of these (on a newly installed snow leo system):

actionmailer (2.3.4, 2.3.3)
actionpack (2.3.4, 2.3.3)
activerecord (2.3.4, 2.3.3)
activeresource (2.3.4, 2.3.3)
activesupport (2.3.4, 2.3.3)
jeremymcanally-context (0.5.5)
nakajima-acts_as_fu (0.0.5)
_open_gem (1.4.0)_
rack (1.0.0)
rails (2.3.4, 2.3.3)
rake (0.8.7)
redgreen (1.2.2)
rubygems-update (1.3.5)
sqlite3-ruby (1.2.5)
validation_reflection (0.3.5)
validatious-on-rails (0.3.5, 0.3.4)

You don't use RVM it seems? Don't recognize "gem1.9"-command

<pre>
grimen@Jonas-Grimfelts-MacBook-Pro:examples/test_app $ ruby -v
ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-darwin10.0.0]
grimen@Jonas-Grimfelts-MacBook-Pro:examples/test_app $ gem -v
1.3.5
</pre>

**Comment by adamsanderson** [comment] 2009-10-10 17:03
ruby1.9 and gem1.9 were install with macports, it gives them the 1.9 suffix so that it doesn't collide with the default ruby 1.8 installation.

You might try installing some other gems that provide ruby gem plugins such as tumbler, and see if they have a similar effect, though I don't want you to end up with a bad install.

**Comment by grimen** [comment] 2009-10-10 17:13
Makes sense, you haven't required the module: require "open_gem/common_options", etc. That's why it can't find it.

http://github.com/adamsanderson/open_gem/blob/master/lib/rubygems/commands/open_command.rb

**Comment by adamsanderson** [comment] 2009-10-10 19:18
It's required in:

http://github.com/adamsanderson/open_gem/blob/master/lib/rubygems_plugin.rb

If you find that moving the `require` fixes the issue, or you find a different solution feel free to fork and patch, but I can't reproduce this issue on my system so I really can't fix it myself.

**Comment by jwhitley** [comment] 2012-04-12 18:43
I'd recommend closing this case.  It doesn't repro with:
- OS X 10.7.3
- Ruby 1.9.3-p125 via rbenv
- `open-gem` 1.4.2
- `technicalpickles-jeweler` 1.2.1
- `rubygems` 1.8.11

**Closed as completed** 2012-05-08 02:42 UTC
Labels: needs repro
